- src/css/products-list.css
- src/js/products-list.js
Відмалювала 6 карток з першої сторінки з API (можливо тут якась інша апішка має бути, бо відмальовує одразу за алфавітом).
Зробила стилізацію для карток  у Мобільній версії.
> відмалювання першої сторінки з API + стилі для мобільної версії

- src/css/products-list.css
- src/js/products-list.js
Доробила мобайл, зробила таблет css + js(кількість відмалювання карток)
> edit some css mobile + css and js for tablet

- src/css/products-list.css
- src/js/products-list.js
> Product list desk

- src/css/products-list.css
- src/js/products-list.js
> edit svg url

- src/css/popular.css
- src/js/popular.js
- src/partials/popular.html
1. додав джс
2. та верстку дlя мобіlьної пристрою
> iteration-1- popular

- src/css/discount.css
- src/js/discount.js
- src/partials/discount.html
> Discount products

- src/css/popular.css
- src/js/popular.js
- src/partials/popular.html
1. розмітка дlя 768 та 1440 px
2. добавив функцію - WithoutUnderscore
> popular-iteration-2

- src/js/local-storage.js
- src/js/products-list.js
слухач на зміну розширення, клік на кошик додає чи видаляє товар з локального сховища.
> changeIconAndLimits

- src/cart-page.html
- src/cart.js
- src/css/cart-page.css
- src/img/icone/symbol-defs.svg
- src/js/cart-page.js
- src/partials/cart.html
Cвітлана, зробила, рендер карток з ЛокалСтор, кнопки видалення окремого продукту та усіх одразу. . Ще загрузила іконку в symbol-defs, бо в мене та що там є некоректно відображалась. Поклацай на продукти, перевір, чи все коректно додається. Потім продовжу далі. Дякую!
> cart-page update

- src/js/products-list.js
Виправив помилку з іконкою, пагідацією та додав перевірку на розмір екрану(якщо екран менше 768 показувати в пагідації лише 2 сторінки)
> fixIconAndvisiblePagesForMobale

- src/js/cart-page.js
Пофіксила дещо в cart-page.js
Закоментований код у файлі cart-js - я потім приберу, коли допишу додаткові завдання. Але перед сдачею на перевірку до ментора - дай знати, я його приберу, щоб було гарно.
> fixed cart-page-js

- src/css/base.css
- src/css/filters.css
- src/js/discount.js
- src/js/filters.js
- src/js/products-list.js
- src/partials/filters.html
- src/partials/products-list.html
1. Додала фільтр пошуку по keyword
2. Додала текст і вивела на сторінку, якщо пошук не дав результатів
3. Додала деякі стилі css
4. Закоментувала filters.js (там немає робочого коду)
5. Відредагувала в пагінації, якщо загальна кількість сторінок 1, то її приховуємо.
> add filter keyword + text result none + some css

- src/css/discount.css
- src/js/discount.js
додав скрол в секцію  Discount та фіналізував стилі
> Discount final version

- src/css/base.css
- src/css/cart-page.css
- src/css/filters.css
- src/css/popular.css
- src/css/products-list.css
- src/js/products-list.js
- src/partials/filters.html
- src/partials/products-list.html
не грузиться/не відображається SVG на інпут категорій та фільтрації (типу галочка)
> no search text apdate + filters css

- src/js/local-storage.js
Додав в обробник кліку зміну кількості товарів в хеадер.
> fixClickHeader

- src/css/popular.css
- src/css/products-list.css
- src/js/local-storage.js
Виправив колір, так функцію для роботи з іконками.
> fixColorAndLocalStorage

- src/css/modal-window.css
- src/js/modal-window.js
- src/partials/modal-window.html
в кінці сторінки кнопка яка реагує на відкриття модального вікна, коли повністю дороблю, приберу
> modal window  mob and tab adaptation + закриття і відкриття модалки

- src/js/popular.js
> popular-iteration-5

- src/css/popular.css
- src/js/products-list.js
1. прибираєм контейнер пагінації, коли лиш 1 відмальована сторінка
2. редагуємо відступи, які з'їхали
3. відмальовуємо кількість карток в залежності від того, який limit у локал сторедж
> виправлення помилок

- src/css/popular.css
- src/css/products-list.css
додала курсор на всі картки і тінь при наведені, також ховер та ектів на кнопки
> add cursor and shadow

- src/css/styles.css
- src/js/filters.js
- src/js/loader.js
- src/js/local-storage.js
- src/js/products-list.js
- src/partials/filters.html
Виправив:
Філтр заміна логіки роботи
Інпут прибирання розмиття
Лоадера заміна кольору
Модал карт  виправлення проблеми кнопка в кнопці
> fixLoaderFilters

- package-lock.json
- package.json
- src/css/modal-cart.css
- src/js/discount.js
- src/js/popular.js
- src/js/products-list.js
npm install simplebar
додавання бібліотеки для скролу в картках
> Scroll fix
